/* eslint-disable @typescript-eslint/no-misused-promises */
import { AlertStatus, IntegrationType, Logger } from '@OpsiMate/shared';
import { AlertBL } from '../bl/alerts/alert.bl';
import { IntegrationBL } from '../bl/integrations/integration.bl';
import { GrafanaClient } from '../dal/external-client/grafana-client';

const logger = new Logger('pull-grafana-alerts-job');

export class PullGrafanaAlertsJob {
	LAbELS_TO_IGNORE = new Set([
		'__alert_rule_uid__',
		'__grafana_autogenerated__',
		'__grafana_receiver__',
		'alertname',
		'datasource_uid',
		'grafana_folder',
		'ref_id',
		'rulename',
	]);
	constructor(
		private alertBL: AlertBL,
		private integrationBL: IntegrationBL
	) {}

	startPullGrafanaAlertsJob = () => {
		logger.info('[Job] Starting refreshAllProvidersServices job (every 10 minutes)');

		// Run immediately on startup (optional)
		this.pullGrafanaAlerts().catch((err) => logger.error('[Job] Initial run failed:', err));

		// Then run every 10 minutes
		setInterval(async () => {
			logger.info('[Job] Running refreshAllProvidersServices');
			try {
				await this.pullGrafanaAlerts();
			} catch (err) {
				logger.error('[Job] Failed to refresh services:', err);
			}
		}, 10 * 1000);
	};

	private async pullGrafanaAlerts() {
		try {
			const grafana = await this.integrationBL.getIntegrationByType(IntegrationType.Grafana);
			if (!grafana) return;

			const token = grafana.credentials['apiKey'] as string;
			if (!token) {
				logger.warn(`No token for Grafana integration ${grafana.name}`);
				return;
			}

			const client = new GrafanaClient(grafana.externalUrl, token);
			const grafanaAlerts = await client.getAlerts();
			const activeAlertIds = new Set(grafanaAlerts.map((a) => a.fingerprint));
			await this.alertBL.archiveNonActiveAlerts(activeAlertIds, 'Grafana');

			for (const alert of grafanaAlerts) {
				const allLabels = alert.labels || {};
				const customTags = Object.fromEntries(
					Object.entries(allLabels).filter(([key]) => !this.LAbELS_TO_IGNORE.has(key))
				);

				try {
					await this.alertBL.insertOrUpdateAlert({
						id: alert.fingerprint,
						type: 'Grafana',
						status: AlertStatus.FIRING,
						tags: customTags,
						startsAt: alert.startsAt ? new Date(alert.startsAt).toISOString() : '',
						updatedAt: alert.updatedAt ? new Date(alert.updatedAt).toISOString() : '',
						alertUrl: alert.generatorURL || '',
						alertName:
							alert.labels?.rulename || alert.labels?.alertname || alert.annotations?.summary || '',
						summary: alert.annotations?.summary || '',
						runbookUrl: alert.annotations?.runbook_url || '',
					});
				} catch (e) {
					logger.error(`Upsert failed for id=${alert.fingerprint}`, e);
				}
			}
		} catch (e) {
			logger.error('[Job] pullGrafanaAlerts failed', e);
		}
	}
}
