export { default as Dashboard } from './Dashboard';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Providers } from './Providers';
export { default as MyProviders } from './MyProviders';
export { default as Integrations } from './Integrations';
export { default as Settings } from './Settings';
export { default as NotFound } from './NotFound';
export { default as Profile } from './Profile';
